### ISSUE TITLE
Error: No ACL setup yet! by using SSO

### ISSUE THREAD

**Issue by sigma5345** [mantisbt/dokuwiki-plugin-authmantis#3]
Hello developers,

I'm using authmantis in the newest version. The configuration is equal to the instructions on this page.
I use the following environement:
- mantisbt version 2.25.2
- dokuwiki "Hoghfather"
- authmantis version from 2020-06-14
- some plugins (EditTable, fontcolor, Redirect, tablelayout)

I have the following problem. Normally the user are already existing in MantisBT database. I expected that they can use SSO with no login to my wiki. Basically it works normal. But when i wanted to open a link to a direct page, for example: https://mydserver.com/dokuwiki/doku.php?id=abc i get an error in the header, footer and sidebar: "No ACL setup yet! Denying access to everyone." and in the mainpage the error is:
 "Zugang verweigert
Sie haben nicht die erforderliche Berechtigung, um diese Aktion durchzuführen. 
Angemeldet als: Domain\Username (Domain\Username)." (Translation: Access denied You do not have the required permission to perform this action. Logged in as:...).
But after I press F5 or reloading the page everything is fine and no errors are shown.

Have you any ideas about this? I hope i made a mistake in my configuration, but I checked everthing twice.

With the best wishes
sigma

![Error_Dokuwiki](https://user-images.githubusercontent.com/92859755/138084512-6bc6b3ca-5d38-4654-8b8d-fc12f4ce187a.png)

**Comment by dregad** [comment]
Hello @sigma5345 apologies for the (very) late reply, I didn't notice this until today... I assume (hope) that you have resolved the problem since then, but in case you have not, I believe it is most likely caused by incorrect ACL config.

Check `conf/acl.auth.php`, and make sure you authorize at least read access for @ALL, e.g.
```
*	@ALL	1
```

For more information on DokuWiki ACLs, read : https://www.dokuwiki.org/acl#access_restrictions
